### PR TITLE
Fix lmul for vsext and vzext

### LINKED ISSUE #26: Tests for vsext.vf4/8 and vzext.vf4/8 rely on inital values of vector registers
The simulator I'm working on currently marks unitialized (vector) registers with `baadf00d`.
With this the test cases for vsext.vf4/8 and vzext.vf4/8 don't pass as they rely on unitialized vector registers:
```
    800188f4:	00200293          	li	t0,2
    800188f8:	0d92f357          	vsetvli	t1,t0,e64,m2,ta,ma
    800188fc:	4902a457          	vsext.vf4	v8,v16,v0.t
    80018900:	00001517          	auipc	a0,0x1
    80018904:	70050513          	add	a0,a0,1792 # 8001a000 <begin_signature>
    80018908:	fff00293          	li	t0,-1
    8001890c:	0db2f357          	vsetvli	t1,t0,e64,m8,ta,ma
    80018910:	02057427          	vse64.v	v8,(a0)
```
In the generated example assembly above `vsext.vf4` is executed with `lmul=2` (max updated registers v8, v9).
When checking the results with `vse64.v` we then use `lmul=8` which accesses vectors v8-v15.
However only v8-v11 have been set by prior writes, v12-v15 are still set to `baadf00d`. (Spike seems to have zero initialized v12-v15)
If I force all vector registers to be zero initialized for the tests, then the tests pass.

Should the tests have a section that initializes all vector registers to zero?
Or would it be better to not have tests that access vector registers that have not been written to yet?
Or is zero initialization required by the spec anyways and I just missed it?

### PR DESCRIPTION
**Pull request by troibe**
The way I read the following lines in the spec is that for `vsext.vf4` or `vzext.vf4` source eew (=sew/4=16) and emul (=lmul/4=1/2) are smaller than the destination eew (=sew=64) and emul (=lmul=2).

> The EEW of the source is 1/2, 1/4, or 1/8 of SEW, while EMUL of the source is (EEW/SEW)*LMUL. The destination has EEW equal to SEW and EMUL equal to LMUL.

Fixed #26

### CODE REVIEW

**Comment by ksco** [comment]
Ah yes, it's the other way around, sorry. But I think my original proposal still is the correct fix -- `vdEMUL` is for `vd`, `c.LMUL1` is for `vs2`.

**Comment by ksco** [comment]
Oh no wait, sorry, the vdEMUL is indeed wrongly calculated.

File: generator/insn_vdvs2vmp3.go [hunk 1]
```diff
@@ -30,22 +30,26 @@ func (i *Insn) genCodeVdVs2VmP3(pos int) []string {
 		builder.WriteString(i.gLoadDataIntoRegisterGroup(0, c.LMUL1, c.SEW))
 
 		vs2EEW := c.SEW / SEW(f)
-		if vs2EEW > SEW(i.Option.XLEN) {
```
Comment (ksco) [inline generator/insn_vdvs2vmp3.go:33]: The if statement can be safely deleted.

File: generator/insn_vdvs2vmp3.go [hunk 2]
```diff
@@ -30,22 +30,26 @@ func (i *Insn) genCodeVdVs2VmP3(pos int) []string {
...
+		if vs2EEW < 8 {
 			res = append(res, "")
 			continue
 		}
 
-		vdEMUL := c.LMUL * LMUL(f)
+		vdEMUL := c.LMUL / LMUL(f)
+		if vdEMUL < 1/8 {
```
Comment (ksco) [inline generator/insn_vdvs2vmp3.go:39]: The if statement is unnecessary.

File: generator/insn_vdvs2vmp3.go [hunk 3]
```diff
@@ -30,22 +30,26 @@ func (i *Insn) genCodeVdVs2VmP3(pos int) []string {
...
 
 		vs2EEW := c.SEW / SEW(f)
-		if vs2EEW > SEW(i.Option.XLEN) {
+		if vs2EEW < 8 {
 			res = append(res, "")
 			continue
 		}
 
-		vdEMUL := c.LMUL * LMUL(f)
+		vdEMUL := c.LMUL / LMUL(f)
```
Comment (ksco) [inline generator/insn_vdvs2vmp3.go:38]: `vdEMUL` does not make sense anymore, `vs2EMUL := c.LMUL / LMUL(f)` should be used.

**Review by ksco — COMMENTED** [review]
There are 4 variables involved:

1. vd EMUL: `c.LMUL1`
2. vd EEW: `c.SEW`
3. vs2 EMUL: `vs2EMUL`
4. vs2 EEW: `vs2EEW`

**Comment by troibe** [comment]
Thanks for the feedback!

**Review by ksco — APPROVED** [review]
Thanks
